parameters:
- name: branch
  displayName: The branch to take the task code from
  default: users/DaniilShmelev/gplayv3
- name: major
  displayName: Extension's major version
  default: 3
- name: minor
  displayName: Extension's minor version
  default: 194
- name: patch
  displayName: Extension's patch version
  default: 0

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
  - repository: gplay
    type: github
    endpoint: DaniilShmelev
    name: microsoft/google-play-vsts-extension

steps:
- checkout: self
- checkout: gplay
- bash: |
    npm i -g tfx-cli
    tfx login --service-url https://v-dshmelev.visualstudio.com/DefaultCollection --token $(PAT)

    cd $(Build.SourcesDirectory)/google-play-vsts-extension
    git checkout ${{ parameters.branch }}

    cd $(Build.SourcesDirectory)/extension-uploader/danilify
    npm i
    node ./index.js $(Build.SourcesDirectory)/google-play-vsts-extension ${{ parameters.major }} ${{ parameters.minor }} ${{ parameters.patch }}

    cd $(Build.SourcesDirectory)/google-play-vsts-extension
    npm i
    node make.js build
    
    gulp installtaskdeps
    gulp cleanpackagefiles

    tfx extension create --manifest-globs vsts-extension-google-play.json
    tfx extension publish --vsix v-dshmelev.DS-google-play-2-${{ parameters.major }}.${{ parameters.minor }}.${{ parameters.patch }}.vsix --token $(PAT)
- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/google-play-vsts-extension/v-dshmelev.DS-google-play-2-${{ parameters.major }}.${{ parameters.minor }}.${{ parameters.patch }}.vsix'
