parameters:
- name: branch
  displayName: The branch to take the task code from
  default: master

trigger: none

pool:
  vmImage: windows-latest

resources:
  repositories:
  - repository: gplay
    type: github
    endpoint: DaniilShmelev
    name: microsoft/google-play-vsts-extension

steps:
- checkout: self
- checkout: gplay
- powershell: |
    npm i -g tfx-cli
    tfx login --service-url https://v-dshmelev.visualstudio.com/DefaultCollection --token $(PAT)

    cd $(Build.SourcesDirectory)/google-play-vsts-extension
    git checkout ${{ parameters.branch }}

    # $ver = $(Build.BuildId)-1500

    cd $(Build.SourcesDirectory)/extension-uploader/danilify
    npm i
    node ./index.js $(Build.SourcesDirectory)/google-play-vsts-extension 0

    cd $(Build.SourcesDirectory)/google-play-vsts-extension
    npm i
    node make.js build

    tfx extension create --manifest-globs vsts-extension-google-play.json
    tfx extension publish --vsix v-dshmelev.DS-google-play-3.194.0.vsix --token $(PAT)
